// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function GetPreferences():Promise<internal.Preferences>;

export function GetServerStatus():Promise<string>;

export function SavePreferences(arg1:internal.Preferences):Promise<void>;
